package com.kaku.colorfulnews.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelDaoConfig;

    private final NewsChannelDao newsChannelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelDaoConfig = daoConfigMap.get(NewsChannelDao.class).clone();
        newsChannelDaoConfig.initIdentityScope(type);

        newsChannelDao = new NewsChannelDao(newsChannelDaoConfig, this);

        registerDao(NewsChannel.class, newsChannelDao);
    }
    
    public void clear() {
        newsChannelDaoConfig.getIdentityScope().clear();
    }

    public NewsChannelDao getNewsChannelDao() {
        return newsChannelDao;
    }

}
